#
# Copyright (C) 2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

obj-y += drivers/extcon/
obj-y += drivers/gpio/
obj-y += drivers/irqchip/
obj-y += drivers/mfd/
obj-y += drivers/regulator/
obj-y += drivers/pinctrl/cirrus/
obj-y += sound/soc/codecs/
