# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -DCONFIG_EXTCON_MADERA_INPUT_EVENT
EXTRA_CFLAGS += -DCONFIG_EXTCON_TACNA_INPUT_EVENT

LINUXINCLUDE += \
	-I$(srctree)/techpack/cirrus/include \
	-I$(srctree)/techpack/cirrus/include/linux

obj-m += extcon-madera.o

# obj-m += extcon-tacna.o
