# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -DCONFIG_PINCTRL_CS47L35

LINUXINCLUDE += \
	-I$(srctree)/techpack/cirrus/include \
	-I$(srctree)/techpack/cirrus/include/linux \
	-I$(srctree)/include \
	-I$(srctree)/drivers/pinctrl

madera-pinctrl-objs = pinctrl-madera.o pinctrl-cs47l35.o
obj-m += madera-pinctrl.o

# irrus_pinctrl-tacna-objs = pinctrl-tacna.o

# ifneq ($(filter m y,$(CONFIG_PINCTRL_CS47L96)),)
#    EXTRA_CFLAGS += -DCONFIG_PINCTRL_CS47L96
# endif

# ifneq ($(filter m y,$(CONFIG_PINCTRL_CS48L32)),)
#     EXTRA_CFLAGS += -DCONFIG_PINCTRL_CS48L32
# endif

# ifneq ($(filter m y,$(CONFIG_PINCTRL_CS48LX50)),)
#     EXTRA_CFLAGS += -DCONFIG_PINCTRL_CS48LX50
# endif

# obj-m += cirrus_pinctrl-tacna.o
