# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

LINUXINCLUDE += \
	-I$(srctree)/techpack/cirrus/include \
	-I$(srctree)/techpack/cirrus/include/linux

obj-m += arizona-ldo1.o arizona-micsupp.o
