# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

LINUXINCLUDE += \
	-I$(srctree)/techpack/cirrus/include \
	-I$(srctree)/techpack/cirrus/include/linux

cirrus_irq-madera-objs = irq-madera.o

obj-m += cirrus_irq-madera.o

# cirrus_irq-tacna-objs = irq-tacna.o

# obj-m += cirrus_irq-tacna.o
